import { NextRequest, NextResponse } from 'next/server';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/auth';
import { prisma } from '@/lib/prisma';
import { razorpay } from '@/lib/razorpay';
import { createOrderSchema } from '@/validators/payment';
import { hashPassword, generateRandomPassword } from '@/lib/password';
import { sendWelcomeEmail } from '@/lib/resend';

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const parsed = createOrderSchema.safeParse(body);

    if (!parsed.success) {
      return NextResponse.json(
        { error: 'Invalid input', details: parsed.error.flatten() },
        { status: 400 }
      );
    }

    const { courseId, email } = parsed.data;

    // Get course
    const course = await prisma.course.findUnique({
      where: { id: courseId, isPublished: true },
    });

    if (!course) {
      return NextResponse.json({ error: 'Course not found' }, { status: 404 });
    }

    // Check session or find/create user
    const session = await getServerSession(authOptions);
    let userId: string;

    if (session) {
      userId = session.user.id;
    } else {
      // Find or create user
      let user = await prisma.user.findUnique({ where: { email } });

      if (!user) {
        const password = generateRandomPassword();
        const passwordHash = await hashPassword(password);

        user = await prisma.user.create({
          data: {
            email,
            passwordHash,
            autoGenerated: true,
          },
        });

        // Send credentials email
        const loginUrl = `${process.env.NEXT_PUBLIC_APP_URL}/login`;
        await sendWelcomeEmail(email, password, loginUrl).catch(console.error);
      }

      userId = user.id;
    }

    // Check if already purchased
    const existingPurchase = await prisma.purchase.findUnique({
      where: { userId_courseId: { userId, courseId } },
    });

    if (existingPurchase?.status === 'COMPLETED') {
      return NextResponse.json({ error: 'Course already purchased' }, { status: 409 });
    }

    // Create Razorpay order
    const order = await razorpay.orders.create({
      amount: course.priceInPaise,
      currency: course.currency,
      receipt: `course_${courseId}_${userId}`,
    });

    // Create/update purchase record
    await prisma.purchase.upsert({
      where: { userId_courseId: { userId, courseId } },
      create: {
        userId,
        courseId,
        razorpayOrderId: order.id,
        amountInPaise: course.priceInPaise,
        currency: course.currency,
        status: 'PENDING',
      },
      update: {
        razorpayOrderId: order.id,
        status: 'PENDING',
      },
    });

    return NextResponse.json({
      orderId: order.id,
      amount: course.priceInPaise,
      currency: course.currency,
      keyId: process.env.NEXT_PUBLIC_RAZORPAY_KEY_ID,
    });
  } catch (error) {
    console.error('Create order error:', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}
