import { prisma } from '@/lib/prisma';
import { UserTable } from '@/components/admin/user-table';

async function getUsers() {
  return prisma.user.findMany({
    include: {
      _count: { select: { purchases: true } },
    },
    orderBy: { createdAt: 'desc' },
  });
}

export default async function AdminUsersPage() {
  let users: Awaited<ReturnType<typeof getUsers>> = [];
  try {
    users = await getUsers();
  } catch {
    // already initialized
  }

  const formattedUsers = users.map((u) => ({
    id: u.id,
    email: u.email,
    name: u.name,
    role: u.role,
    autoGenerated: u.autoGenerated,
    purchaseCount: u._count.purchases,
    createdAt: u.createdAt.toISOString(),
  }));

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-heading font-bold">Users</h1>
        <p className="text-white/40 mt-1">{users.length} total users</p>
      </div>
      <UserTable users={formattedUsers} />
    </div>
  );
}
