'use client';

import { useState } from 'react';
import { Badge } from '@/components/ui/badge';

interface User {
  id: string;
  email: string;
  name: string | null;
  role: 'STUDENT' | 'ADMIN';
  autoGenerated: boolean;
  purchaseCount: number;
  createdAt: string;
}

export function UserTable({ users }: { users: User[] }) {
  const [search, setSearch] = useState('');

  const filtered = users.filter(
    (u) =>
      u.email.toLowerCase().includes(search.toLowerCase()) ||
      u.name?.toLowerCase().includes(search.toLowerCase())
  );

  return (
    <div className="space-y-4">
      <input
        type="text"
        placeholder="Search by email or name..."
        value={search}
        onChange={(e) => setSearch(e.target.value)}
        className="w-full max-w-sm px-4 py-2 rounded-lg bg-black-800 border border-white/10 text-white placeholder-surface-500 focus:outline-none focus:border-primary/60 text-sm"
      />

      <div className="rounded-xl border border-white/10 overflow-hidden">
        <table className="w-full text-sm">
          <thead>
            <tr className="bg-black-900 border-b border-white/10">
              <th className="text-left p-4 text-white/40 font-medium">Email</th>
              <th className="text-left p-4 text-white/40 font-medium">Name</th>
              <th className="text-left p-4 text-white/40 font-medium">Role</th>
              <th className="text-left p-4 text-white/40 font-medium">Purchases</th>
              <th className="text-left p-4 text-white/40 font-medium">Joined</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-surface-800">
            {filtered.map((user) => (
              <tr key={user.id} className="hover:bg-black-900/50 transition-colors">
                <td className="p-4">
                  <div className="flex items-center gap-2">
                    <span>{user.email}</span>
                    {user.autoGenerated && (
                      <Badge variant="gray">Auto</Badge>
                    )}
                  </div>
                </td>
                <td className="p-4 text-white/50">{user.name || '—'}</td>
                <td className="p-4">
                  <Badge variant={user.role === 'ADMIN' ? 'gold' : 'gray'}>
                    {user.role}
                  </Badge>
                </td>
                <td className="p-4 text-white/50">{user.purchaseCount}</td>
                <td className="p-4 text-white/30">
                  {new Date(user.createdAt).toLocaleDateString()}
                </td>
              </tr>
            ))}
          </tbody>
        </table>

        {filtered.length === 0 && (
          <div className="p-8 text-center text-white/30">No users found</div>
        )}
      </div>
    </div>
  );
}
